package com.holytrinity.model

data class Document(
    val document_id: Int,
    val doc_type: String,
    val file_name: String,
    val file_path: String,
    val upload_date: String,
    val verified: Int
)

data class Student(

    val student_id: String? = null,
    val entry_period_id: String? = null,
    val curriculum_id: String? = null,
    val full_name: String? = null,
    val student_name: String? = null,
    val email: String? = null,
    val phone: String? = null,
    val curr_id: String? = null,
    val dept_id: String? = null,
    val course: String? = null,
    val level: String? = null,
    val official_status: String? = null,
    val section: String? = null,
    val classification_of_student: String? = null,
    val birthdate: String? = null,
    val gender: String? = null,
    val address: String? = null,
    val learner_ref_no: String? = null,
    val attended: String? = null,
    val course_name: String? = null,
    val form137: String? = null,
    val diploma: String? = null,
    val tor: String? = null,
    val coh: String? = null,
    val esc: String? = null,
    val userName: String? = null,
    val password: String? = null,
    val baptismal: List<Document>? = null, // Change to List<Document>
    val confirmCert: List<Document>? = null, // Change to List<Document>
    val nso: String? = null,
    val marriageCert: String? = null,
    val brgyCert: String? = null,
    val indigency: String? = null,
    val birForm: String? = null,
    val recommLetter: String? = null,
    val parish: String? = null,
    val medCert: String? = null,
    val userType: String? = null,
    val fullName: String? = null,
    val last_name: String? = null,
    val first_name: String? = null,
    val line1: String? = null,
    val balance: String? = null,
    val line2: String? = null,
    val middle_name: String? = null,
    val municipality: String? = null,
    val barangay: String? = null,
    val curriculum: String? = null,
    val entryPeriod: String? = null,
    val createdAt: String? = null,
    val dateOfBirth: String? = null,
    val registration_verified: String? = null,
    val entry_date: String? = null,
    val user_id: String? = null,
    val documents: List<Document>? = null
)
